import { defineConfig } from "vitepress";

export default defineConfig({
  title: "PostgreSQL Transactions",
  description:
    "Learn PostgreSQL transactions from verified, runnable examples — every claim proven against a real database.",
  base: "/postgres-transactions/",
  cleanUrls: true,
  // Generated transcript fragments are included into lesson pages, never built as pages.
  srcExclude: ["**/parts/**"],
  themeConfig: {
    nav: [
      { text: "Start learning", link: "/01-basics/what-is-a-transaction" },
      { text: "Methodology", link: "/about/methodology" },
    ],
    sidebar: [
      {
        text: "About",
        items: [
          { text: "Why trust this site?", link: "/about/methodology" },
          { text: "Run it locally", link: "/about/run-locally" },
        ],
      },
      {
        text: "1. Transactions 101",
        items: [
          { text: "What is a transaction?", link: "/01-basics/what-is-a-transaction" },
          { text: "BEGIN, COMMIT, ROLLBACK", link: "/01-basics/begin-commit-rollback" },
          { text: "Savepoints", link: "/01-basics/savepoints" },
        ],
      },
      {
        text: "2. Isolation levels & anomalies",
        items: [
          { text: "Snapshots & the four levels", link: "/02-isolation/snapshots-and-the-four-levels" },
          { text: "Read Committed", link: "/02-isolation/read-committed" },
          { text: "Repeatable Read", link: "/02-isolation/repeatable-read" },
          { text: "Serializable", link: "/02-isolation/serializable" },
          { text: "Lost updates", link: "/02-isolation/lost-update" },
          { text: "The anomaly catalog", link: "/02-isolation/anomaly-catalog" },
        ],
      },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/svyatov/postgres-transactions" }],
    search: { provider: "local" },
    outline: [2, 3],
    footer: {
      message: "MIT Licensed · Every transcript on this site was generated by a real PostgreSQL run.",
      copyright: "© 2026 Leonid Svyatov",
    },
  },
});
