import { defineConfig } from "vitepress";

export default defineConfig({
  title: "PostgreSQL Transactions",
  description:
    "Learn PostgreSQL transactions from verified, runnable examples — every claim proven against a real database.",
  base: "/postgres-transactions/",
  cleanUrls: true,
  // Generated transcript fragments are included into lesson pages, never built as pages.
  srcExclude: ["**/parts/**"],
  themeConfig: {
    nav: [
      { text: "Start learning", link: "/01-basics/what-is-a-transaction" },
      { text: "Methodology", link: "/about/methodology" },
    ],
    sidebar: [
      {
        text: "About",
        items: [
          { text: "Why trust this site?", link: "/about/methodology" },
          { text: "Run it locally", link: "/about/run-locally" },
        ],
      },
      {
        text: "1. Transactions 101",
        items: [
          { text: "What is a transaction?", link: "/01-basics/what-is-a-transaction" },
          { text: "BEGIN, COMMIT, ROLLBACK", link: "/01-basics/begin-commit-rollback" },
          { text: "Savepoints", link: "/01-basics/savepoints" },
        ],
      },
      {
        text: "2. Isolation levels & anomalies",
        items: [
          { text: "Snapshots & the four levels", link: "/02-isolation/snapshots-and-the-four-levels" },
          { text: "Read Committed", link: "/02-isolation/read-committed" },
          { text: "Repeatable Read", link: "/02-isolation/repeatable-read" },
          { text: "Serializable", link: "/02-isolation/serializable" },
          { text: "Lost updates", link: "/02-isolation/lost-update" },
          { text: "The anomaly catalog", link: "/02-isolation/anomaly-catalog" },
        ],
      },
      {
        text: "3. Locking",
        items: [
          { text: "Row locks", link: "/03-locking/row-locks" },
          { text: "Lock queues", link: "/03-locking/lock-queues" },
          { text: "NOWAIT, lock_timeout, SKIP LOCKED", link: "/03-locking/nowait-skip-locked" },
          { text: "Table locks & DDL", link: "/03-locking/table-locks-and-ddl" },
          { text: "Deadlocks", link: "/03-locking/deadlocks" },
          { text: "Monitoring locks", link: "/03-locking/monitoring-locks" },
        ],
      },
      {
        text: "4. MVCC under the hood",
        items: [
          { text: "Row versions: xmin, xmax, ctid", link: "/04-mvcc/row-versions" },
          { text: "Snapshots under the hood", link: "/04-mvcc/snapshots-under-the-hood" },
          { text: "Dead tuples & bloat", link: "/04-mvcc/dead-tuples-and-bloat" },
          { text: "VACUUM", link: "/04-mvcc/vacuum" },
          { text: "Long transactions", link: "/04-mvcc/long-transactions" },
          { text: "Transaction ID wraparound", link: "/04-mvcc/wraparound" },
        ],
      },
      {
        text: "5. Real-world patterns",
        items: [
          { text: "Fixing lost updates", link: "/05-patterns/fixing-lost-updates" },
          { text: "Retrying serialization failures", link: "/05-patterns/retrying-serialization-failures" },
          { text: "A SKIP LOCKED job queue", link: "/05-patterns/job-queue" },
          { text: "Advisory locks", link: "/05-patterns/advisory-locks" },
          { text: "Check-then-insert", link: "/05-patterns/check-then-insert" },
          { text: "Idempotency keys", link: "/05-patterns/idempotency" },
          { text: "ORM pitfalls", link: "/05-patterns/orm-pitfalls" },
        ],
      },
      {
        text: "6. Transactions across services",
        items: [
          { text: "Dual writes & the outbox", link: "/06-distributed/transactional-outbox" },
          { text: "LISTEN/NOTIFY", link: "/06-distributed/listen-notify" },
          { text: "Sagas", link: "/06-distributed/sagas" },
          { text: "Two-phase commit", link: "/06-distributed/two-phase-commit" },
        ],
      },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/svyatov/postgres-transactions" }],
    search: { provider: "local" },
    outline: [2, 3],
    footer: {
      message: "MIT Licensed · Every transcript on this site was generated by a real PostgreSQL run.",
      copyright: "© 2026 Leonid Svyatov",
    },
  },
});
