/**
 * Runs every scenario against the real database and writes its transcript to
 * docs/<db>/<chapter>/parts/<scenario>.md, where lesson pages include it.
 *
 * CI regenerates all transcripts and fails on any diff — the docs cannot drift
 * from actual database behavior.
 *
 * The same pass records what it proved: docs/public/ledger.jsonl plus llms-full.txt
 * and llms.txt — all committed, inside the drift gate, so a prose-only CI run that
 * skips `gen` still ships them.
 */
import { rm } from "node:fs/promises";
import { type Dialect, dialectFor } from "../harness/dialect";
import { loadScenario } from "../harness/loader";
import { runScenario } from "../harness/run";
import { renderMarkdown, renderTimeline } from "../harness/transcript";

const REPO = "https://github.com/svyatov/database-transactions";
const SITE = "https://svyatov.github.io/database-transactions";
const root = new URL("..", import.meta.url).pathname;

const versions = new Map<Dialect, string>();
async function versionOf(dialect: Dialect): Promise<string> {
  if (!versions.has(dialect)) {
    const sql = dialect.connect(1);
    versions.set(dialect, await dialect.version(sql));
    await sql.close();
  }
  return versions.get(dialect)!;
}

/**
 * One ledger record. Keys are emitted in this order and error codes are sorted, so
 * re-serialization is byte-stable — nothing here may vary between two runs against
 * the same pinned versions, or the drift gate goes red on a green build.
 */
interface Ledger {
  scenario: string;
  engine: string;
  product: string;
  version: string;
  claim: string;
  sessions: string[];
  errors: string[];
  anomaly?: string;
  isolation?: string;
}

selfTest();

// pytest writes this on a clean session; the footer renders its cross-driver clause only
// when it exists. Destroy it first: whatever it proved, it proved about older transcripts.
await rm(`${root}.cross-driver-ok`, { force: true });

const records: Ledger[] = [];
const transcripts: string[] = [];

const files = [...new Bun.Glob("**/*.{ts,yaml}").scanSync({ cwd: `${root}scenarios` })].sort();
for (const file of files) {
  const s = await loadScenario(`${root}scenarios/${file}`);
  const dialect = dialectFor(file);
  const result = await runScenario(s, dialect);
  const version = await versionOf(dialect);
  const target = `docs/${file.replace(/\/([^/]+)\.(ts|yaml)$/, "/parts/$1.md")}`;
  const timeline = renderTimeline(result);
  const transcript = [
    ...(timeline ? [timeline, ""] : []),
    renderMarkdown(result, dialect).trimEnd(),
    "",
    `<small>Verified against ${dialect.product} ${version} · [Run it yourself](/about/run-locally) · [Scenario source](${REPO}/blob/main/scenarios/${file})</small>`,
    "",
  ].join("\n");
  await Bun.write(
    root + target,
    `<!-- GENERATED by \`bun run gen\` from scenarios/${file} — do not edit by hand. -->\n\n${transcript}`,
  );

  // Both kinds: a deadlock victim's error arrives as `resume-error`, on the statement it
  // fired with `.blocked`. A filter that matched only `error` would silently drop it.
  const errors = result.events.flatMap((e) => (e.kind === "error" || e.kind === "resume-error" ? [e.error.code] : []));
  records.push({
    scenario: file,
    engine: file.split("/")[0]!,
    product: dialect.product,
    version,
    claim: s.claim,
    sessions: [...s.sessions],
    errors: [...new Set(errors)].sort(),
    ...(s.anomaly ? { anomaly: s.anomaly } : {}),
    ...(s.isolation ? { isolation: s.isolation } : {}),
  });
  transcripts.push(transcript);
  console.log(`✓ ${target}`);
}

await Bun.write(`${root}docs/public/ledger.jsonl`, `${records.map((r) => JSON.stringify(r)).join("\n")}\n`);
await Bun.write(`${root}docs/public/llms-full.txt`, llmsFull(records, transcripts));
await Bun.write(`${root}docs/public/llms.txt`, llmsIndex());
console.log(`✓ docs/public/ledger.jsonl (${records.length} records), llms-full.txt, llms.txt`);

/** A claim as one line — YAML folds them already, but a `.ts` scenario need not. */
function oneLine(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/**
 * Every transcript behind a heading that attributes it. The concatenation also checks
 * itself: parse the rendered text back and demand one section per record, path and claim
 * matching — so a dropped or mispaired transcript fails here at gen time with a precise
 * message, not later as an opaque line in the drift gate that now covers this file too.
 */
function llmsFull(records: Ledger[], transcripts: string[]): string {
  if (transcripts.length !== records.length || transcripts.some((t) => !t.trim())) {
    throw new Error(
      `llms-full.txt: ${records.length} records but ${transcripts.filter((t) => t?.trim()).length} transcripts`,
    );
  }
  const out = [
    "# Database Transactions — every proven transcript",
    "",
    `Each section below is one scenario, replayed against a real database by \`bun run gen\`.`,
    `The structured index of the same runs is at ${SITE}/ledger.jsonl.`,
    "",
    ...records.flatMap((r, i) => [
      `## ${r.scenario}`,
      "",
      `- engine: ${r.engine} (${r.product} ${r.version})`,
      `- claim: ${oneLine(r.claim)}`,
      "",
      transcripts[i]!,
    ]),
  ].join("\n");

  const sections = [...out.matchAll(/^## (.+)\n\n- engine: .+\n- claim: (.+)$/gm)];
  if (sections.length !== records.length) {
    throw new Error(`llms-full.txt has ${sections.length} sections, ledger has ${records.length} records`);
  }
  records.forEach((r, i) => {
    const [, scenario, claim] = sections[i]!;
    if (scenario !== r.scenario || claim !== oneLine(r.claim)) {
      throw new Error(`llms-full.txt section ${i + 1} is "${scenario}", ledger record is "${r.scenario}"`);
    }
  });
  return out;
}

function llmsIndex(): string {
  return [
    "# Database Transactions",
    "",
    "> Transaction behavior on PostgreSQL and MySQL, taught from transcripts of real database",
    "> runs. Every claim on this site is proven by a scenario that CI replays against pinned",
    "> engine versions on every push, and fails on any drift.",
    "",
    "## Proofs",
    "",
    `- [Every proven transcript](${SITE}/llms-full.txt): all scenarios, with the SQL, the interleaving, and the database's own output.`,
    `- [Ledger](${SITE}/ledger.jsonl): one JSON Lines record per scenario — path, engine, pinned version, claim, sessions, observed error codes. No schema-stability guarantee; the shape grows as the site does.`,
    `- [Error codes, reproduced](${SITE}/errors/): the seven concurrency-control codes (PostgreSQL and MySQL), each with a one-sentence answer and the minimal reproduction that emits it.`,
    `- [FAQ](${SITE}/faq): the questions people actually ask — dirty reads, lost updates, deadlocks, isolation levels — each answered in a sentence or two and linked to the transcript that proves it.`,
    "",
  ].join("\n");
}

/** A guard that has never failed proves nothing. Runs on every `gen`. */
function selfTest() {
  const rec = (scenario: string, claim: string): Ledger => ({
    scenario,
    engine: "postgres",
    product: "PostgreSQL",
    version: "18.4",
    claim,
    sessions: ["A"],
    errors: [],
  });
  const two = [rec("a.yaml", "claim a"), rec("b.yaml", "claim b")];
  const bodies = ["body a", "body b"];
  const forged = "## c.yaml\n\n- engine: postgres (PostgreSQL 18.4)\n- claim: forged\n";

  llmsFull(two, bodies); // the happy path renders
  const cases: Array<[string, () => unknown]> = [
    ["a dropped transcript", () => llmsFull(two, bodies.slice(0, 1))],
    ["an empty transcript", () => llmsFull(two, ["body a", "  "])],
    ["a transcript forging a section", () => llmsFull(two, ["body a", forged])],
  ];
  for (const [name, render] of cases) {
    let threw = false;
    try {
      render();
    } catch {
      threw = true;
    }
    if (!threw) throw new Error(`self-test failed: ${name} passed the llms-full.txt check`);
  }
}
