/**
 * Runs every scenario against the real database and writes its transcript to
 * docs/<db>/<chapter>/parts/<scenario>.md, where lesson pages include it.
 *
 * CI regenerates all transcripts and fails on any diff — the docs cannot drift
 * from actual database behavior.
 */
import { type Dialect, dialectFor } from "../harness/dialect";
import { loadScenario } from "../harness/loader";
import { runScenario } from "../harness/run";
import { renderMarkdown } from "../harness/transcript";

const REPO = "https://github.com/svyatov/database-transactions";
const root = new URL("..", import.meta.url).pathname;

const versions = new Map<Dialect, string>();
async function versionOf(dialect: Dialect): Promise<string> {
  if (!versions.has(dialect)) {
    const sql = dialect.connect(1);
    versions.set(dialect, await dialect.version(sql));
    await sql.close();
  }
  return versions.get(dialect)!;
}

const files = [...new Bun.Glob("**/*.{ts,yaml}").scanSync({ cwd: `${root}scenarios` })].sort();
for (const file of files) {
  const s = await loadScenario(`${root}scenarios/${file}`);
  const dialect = dialectFor(file);
  const result = await runScenario(s, dialect);
  const target = `docs/${file.replace(/\/([^/]+)\.(ts|yaml)$/, "/parts/$1.md")}`;
  const content = [
    `<!-- GENERATED by \`bun run gen\` from scenarios/${file} — do not edit by hand. -->`,
    "",
    renderMarkdown(result, dialect).trimEnd(),
    "",
    `<small>Verified against ${dialect.product} ${await versionOf(dialect)} · [Run it yourself](/about/run-locally) · [Scenario source](${REPO}/blob/main/scenarios/${file})</small>`,
    "",
  ].join("\n");
  await Bun.write(root + target, content);
  console.log(`✓ ${target}`);
}
